/**
 * Universal AI Code Fingerprint Detector & Rule-Based Sanitizer Engine
 * Works for ANY project type: React, Node.js, Python, PHP/WordPress, HTML/CSS, SQL, Go, Java, etc.
 */

export interface DetectedTrigger {
  id: string;
  category: 'formatting' | 'robotic_comments' | 'unidiomatic_structure' | 'security_risk' | 'performance';
  title: string;
  hinglishDesc: string;
  englishDesc: string;
  severity: 'high' | 'medium' | 'low';
  occurrences: number;
  sampleLine?: string;
  solution: string;
}

export interface AnalysisResult {
  aiProbabilityScore: number;
  summary: string;
  hinglishSummary: string;
  triggers: DetectedTrigger[];
  stats: {
    originalLines: number;
    cleanedLines: number;
    emptyLinesCount: number;
    bannerCommentsCount: number;
    trivialCommentsCount: number;
    sparseWrapsCount: number;
  };
}

export interface SanitizerOptions {
  condenseVerticalSprawl: boolean;
  removeRoboticBanners: boolean;
  cleanTrivialComments: boolean;
  normalizeBlankLines: boolean;
  removeInlineStyles: boolean;
  hardenSecurity: boolean;
}

export const DEFAULT_OPTIONS: SanitizerOptions = {
  condenseVerticalSprawl: true,
  removeRoboticBanners: true,
  cleanTrivialComments: true,
  normalizeBlankLines: true,
  removeInlineStyles: true,
  hardenSecurity: true,
};

/**
 * Detect AI fingerprints in ANY code language (JS/TS, Python, PHP, HTML/CSS, SQL, etc.)
 */
export function analyzeCodeLocal(code: string, language: string = 'javascript'): AnalysisResult {
  const lines = code.split(/\r?\n/);
  const totalLines = lines.length;

  let emptyLinesCount = 0;
  let bannerCommentsCount = 0;
  let trivialCommentsCount = 0;
  let sparseWrapsCount = 0;
  const triggers: DetectedTrigger[] = [];

  // 1. Extreme vertical sprawl check (Universal across all languages)
  let consecutiveShortLines = 0;
  let maxConsecutiveShortLines = 0;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();
    if (line === '') {
      emptyLinesCount++;
      consecutiveShortLines = 0;
      continue;
    }

    // Single-word line tokens, broken parameters, single operators
    const isSingleWordWrap =
      /^[a-zA-Z0-9_\$'"\\\/]+[,;=]?$/.test(line) ||
      /^[,\(\)\{\}\[\];]$/.test(line) ||
      /^\);?$/.test(line) ||
      /^array\($/.test(line) ||
      /^true|false|null|undefined[,;]?$/i.test(line);

    if (isSingleWordWrap) {
      sparseWrapsCount++;
      consecutiveShortLines++;
      if (consecutiveShortLines > maxConsecutiveShortLines) {
        maxConsecutiveShortLines = consecutiveShortLines;
      }
    } else {
      consecutiveShortLines = 0;
    }
  }

  if (sparseWrapsCount > 10 || maxConsecutiveShortLines >= 3) {
    triggers.push({
      id: 'vertical_sprawl',
      category: 'formatting',
      title: 'Extreme Vertical Sprawl (Single-Word Lines)',
      hinglishDesc: 'AI ne code ke variables, function arguments aur array items ko 1-1 shabd ki lines me tod diya hai. Is wajah se normal code 3x se 5x lamba ho jata hai jo turant AI-written pehchana jata hai.',
      englishDesc: 'AI models split simple assignments, function arguments, and object properties across single-token lines, artificially inflating line count.',
      severity: 'high',
      occurrences: sparseWrapsCount,
      sampleLine: 'const email =\\n    req.body.email; OR function(a,\\n b,\\n c)',
      solution: 'Condense into standard single-line assignments and idiomatic multi-line argument groups.',
    });
  }

  // 2. Robotic ASCII / Box / Divider banners (Universal)
  const bannerPatterns = [
    /\/\*\s*\|[-=_]{8,}[\s\S]*?\|[-=_]{8,}\s*\*\//g,
    /\/\*[\s\S]*?={15,}[\s\S]*?\*\//g,
    /<!--[\s\S]*?={15,}[\s\S]*?-->/g,
    /"""[\s\S]*?={15,}[\s\S]*?"""/g,
    /\/\/\s*[-=_]{15,}\s*$/gm,
    /#\s*[-=_]{15,}\s*$/gm,
    /--\s*={15,}\s*$/gm,
  ];

  for (const pat of bannerPatterns) {
    const matches = code.match(pat);
    if (matches) {
      bannerCommentsCount += matches.length;
    }
  }

  if (bannerCommentsCount > 0) {
    triggers.push({
      id: 'robotic_banners',
      category: 'robotic_comments',
      title: 'Robotic ASCII Divider Banners',
      hinglishDesc: `Code me ${bannerCommentsCount} mechanical section divider banners mile (/* |---------| */ ya /* ======= */). Real human developers har 10 lines me aise decorative borders nahi banate.`,
      englishDesc: `Found ${bannerCommentsCount} mechanical ASCII decorative box borders generated by AI prompt templates.`,
      severity: 'high',
      occurrences: bannerCommentsCount,
      sampleLine: '/* |---------------------------------------------------------- | User Auth Controller |---------------------------------------------------------- */',
      solution: 'Remove decorative ASCII borders; use standard concise comments or JSDoc/DocStrings only when necessary.',
    });
  }

  // 3. Stating-the-Obvious / Step-by-Step AI Comments
  const trivialCommentPatterns = [
    /\/\/\s*(Step\s+\d+:|Read|Get|Extract|Validate|Check if|Return|Save|Send|Log)\s+[a-zA-Z0-9_\s]{2,30}$/gmi,
    /#\s*(Step\s+\d+:|Extract|Validate|Check if|Return|Set up|Log)\s+[a-zA-Z0-9_\s]{2,30}$/gmi,
    /--\s*(Step\s+\d+:|Select columns|Join|Filter|Group|Sort|Order)\s+[a-zA-Z0-9_\s]{2,30}$/gmi,
    /\/\*\s*\n?\s*\*\s*(Step\s+\d+:|Read|Get|Find|Save|Check|First row|Empty|Duplicate)\b[^\n*]*\n?\s*\*\//gi,
  ];

  for (const pattern of trivialCommentPatterns) {
    const matches = code.match(pattern);
    if (matches) {
      trivialCommentsCount += matches.length;
    }
  }

  if (trivialCommentsCount > 3) {
    triggers.push({
      id: 'trivial_comments',
      category: 'robotic_comments',
      title: 'Robotic Step-by-Step & Obvious Comments',
      hinglishDesc: `Code me ${trivialCommentsCount} "Step 1: Get email", "Step 2: Read password", "Return result" jaise obvious comments mile jo code padhne wale ko turant bata dete hain ki yeh AI se copy-paste kiya gaya hai.`,
      englishDesc: `Identified ${trivialCommentsCount} hyper-redundant step-by-step comments ("Step 1: Read value", "Check if empty") that merely repeat what the code literally states.`,
      severity: 'medium',
      occurrences: trivialCommentsCount,
      sampleLine: '// Step 1: Read email from body\\nconst email = req.body.email;',
      solution: 'Strip redundant line-by-line comments, preserving only high-value architectural context.',
    });
  }

  // 4. Excessive Blank Lines
  const emptyRatio = emptyLinesCount / (totalLines || 1);
  if (emptyRatio > 0.22 && emptyLinesCount > 15) {
    triggers.push({
      id: 'excessive_blank_lines',
      category: 'formatting',
      title: 'Bloated Spacing (Excessive Blank Lines)',
      hinglishDesc: `Code ki lagbhag ${Math.round(emptyRatio * 100)}% lines sirf empty blanks hain (${emptyLinesCount} lines).`,
      englishDesc: `Over ${Math.round(emptyRatio * 100)}% of the file is consumed by repetitive empty blank line padding.`,
      severity: 'medium',
      occurrences: emptyLinesCount,
      solution: 'Normalize to 1 blank line between logical function and class blocks.',
    });
  }

  // 5. Language-Specific Smells
  // Node / Express / JS
  if (code.includes('console.log') && (code.includes('express') || code.includes('req.body') || code.includes('export '))) {
    triggers.push({
      id: 'console_logs',
      category: 'performance',
      title: 'Raw console.log in Production Code',
      hinglishDesc: 'Catch block me raw console.log(error) chuta hua hai jo production application me memory leak aur sensitive data leak kar sakta hai.',
      englishDesc: 'Unstructured console.log calls left in catch blocks rather than using a production logger or clean error handler.',
      severity: 'low',
      occurrences: (code.match(/console\.log/g) || []).length,
      solution: 'Replace with proper error logging or structured exception handling.',
    });
  }

  // HTML inline style dumps
  if (code.includes('style="') && (code.match(/style="/g) || []).length >= 3) {
    triggers.push({
      id: 'inline_styles',
      category: 'unidiomatic_structure',
      title: 'Hardcoded Inline Styles in Markup',
      hinglishDesc: 'HTML tags par inline style="..." hardcoded hai jo site ke design system ya Tailwind/CSS classes ko bypass karta hai.',
      englishDesc: 'Heavy raw inline CSS style attributes mixed directly into markup instead of clean CSS/Tailwind classes.',
      severity: 'medium',
      occurrences: (code.match(/style="/g) || []).length,
      solution: 'Extract into CSS classes or clean design system utilities.',
    });
  }

  // Calculate score based on triggers
  let score = 20;
  if (sparseWrapsCount > 8) score += 35;
  if (bannerCommentsCount > 0) score += 25;
  if (trivialCommentsCount > 3) score += 15;
  if (emptyRatio > 0.22) score += 10;
  score = Math.min(score, 98);

  const hinglishSummary = score > 60
    ? `Yeh code saaf AI-generated lagta hai (${score}% AI score). Isme 3 sabse common AI signatures hain: 1) Har variable aur function call 4-8 lines me toota hua hai, 2) Decorative ASCII divider banners, aur 3) Har line par "Step 1: ...", "Step 2: ..." jaise repetitive comments. Clean karne ke baad yeh bilkul clean, human senior developer jaisa dikhega aur kisi bhi project me directly lagaya ja sakega.`
    : `Code me minor AI artifacts hain. Fast clean ya Deep Humanize use karke isko kisi bhi production project ke standard format me laya ja sakta hai.`;

  return {
    aiProbabilityScore: score,
    summary: `Identified ${triggers.length} AI generation signatures (${score}% AI probability). Features vertical token sprawl, decorative ASCII headers, and step-by-step commentary.`,
    hinglishSummary,
    triggers,
    stats: {
      originalLines: totalLines,
      cleanedLines: 0,
      emptyLinesCount,
      bannerCommentsCount,
      trivialCommentsCount,
      sparseWrapsCount,
    },
  };
}

/**
 * Universal Rule-Based Sanitizer: instantly cleans ANY code language
 */
export function sanitizeCodeLocal(
  rawCode: string,
  options: SanitizerOptions = DEFAULT_OPTIONS
): { cleanedCode: string; originalLines: number; cleanedLines: number; linesReduced: number } {
  let code = rawCode;

  // 1. Strip markdown wrapper backticks
  code = code.replace(/^```[a-z0-9_\-]*\r?\n/i, '');
  code = code.replace(/\r?\n```\s*$/i, '');

  // 2. Remove mechanical ASCII divider banners (JS, PHP, CSS, HTML, Python, SQL)
  if (options.removeRoboticBanners) {
    // /* |--- Title ---| */
    code = code.replace(
      /\/\*\s*\n\s*\|[-=_]{8,}\s*\n\s*\|\s*([^\n|]+)\s*\n\s*\|[-=_]{8,}\s*\n\s*\*\//g,
      (match, title) => `\n// ${title.trim()}`
    );

    // /* ====== Title ====== */
    code = code.replace(
      /\/\*\s*\n?\s*={10,}\s*\n\s*([^\n=]+)\s*\n\s*={10,}\s*\n?\s*\*\//g,
      (match, title) => `\n// ${title.trim()}`
    );

    // HTML <!-- ====== Title ====== -->
    code = code.replace(
      /<!--\s*\n?\s*={10,}\s*\n\s*([^\n=]+)\s*\n\s*={10,}\s*\n?\s*-->/g,
      (match, title) => `<!-- ${title.trim()} -->`
    );

    // Python """ ====== Title ====== """
    code = code.replace(
      /"""\s*\n?\s*={10,}\s*\n\s*([^\n=]+)\s*\n\s*={10,}\s*\n?\s*"""/g,
      (match, title) => `# ${title.trim()}`
    );

    // SQL /* ===== Title ===== */
    code = code.replace(
      /\/\*\s*\n?\s*={10,}\s*\n([\s\S]*?)\n\s*={10,}\s*\n?\s*\*\//g,
      (match, content) => {
        const firstLine = content.split('\n')[0].trim();
        return firstLine ? `-- ${firstLine}` : '';
      }
    );

    // General multi-line divider boxes
    code = code.replace(/\/\*\s*\|[-=_]{8,}[\s\S]*?\|[-=_]{8,}\s*\*\//g, '');
    code = code.replace(/\/\/\s*[-=_]{12,}\s*$/gm, '');
    code = code.replace(/#\s*[-=_]{12,}\s*$/gm, '');
  }

  // 3. Remove robotic trivial & step-by-step comments
  if (options.cleanTrivialComments) {
    // JS/TS/PHP // Step 1: ..., // Read ...
    code = code.replace(
      /\/\/\s*(Step\s+\d+:|Read|Get|Find|Save|Extract|Validate|Check if empty|Check if user|Return\s+[a-z]+|Log error|Prevent default|Set submitting)\b[^\n]*\n/gi,
      ''
    );

    // Python # Step 1: ...
    code = code.replace(
      /#\s*(Step\s+\d+:|Check if|Extract|Validate|Log missing|Return sanitized)\b[^\n]*\n/gi,
      ''
    );

    // SQL -- Step 1: ...
    code = code.replace(
      /--\s*(Step\s+\d+:|Select columns|Join|Filter|Group|Sort|Order)\b[^\n]*\n/gi,
      ''
    );

    // Multi-line /* Read Title */
    code = code.replace(
      /\/\*\s*\n?\s*\*\s*(Step\s+\d+:|Read|Get|Find|Save|Detect|Check|First row = headers|Empty title = failed|Duplicate = Skip|Duplicate = Update|Create new|Save Video|Save Tracking)\b[^\n*]*\n?\s*\*\/\s*\n/gi,
      ''
    );
  }

  // 4. Condense exaggerated single-token vertical wraps
  if (options.condenseVerticalSprawl) {
    // Variable assignments: const a =\n    b; or $a =\n    b;
    code = code.replace(/((?:const|let|var|\$)[a-zA-Z0-9_]+)\s*=\s*\n\s+([^\n;]+;)/g, '$1 = $2');

    // JS/TS object / array properties: key:\n    val,
    code = code.replace(/([a-zA-Z0-9_]+):\s*\n\s+([a-zA-Z0-9_\$'"\\\/]+),/g, '$1: $2,');

    // Function calls across lines:
    for (let pass = 0; pass < 3; pass++) {
      // 1-arg or 2-arg function calls
      code = code.replace(
        /([a-zA-Z0-9_]+)\(\s*\n\s+([a-zA-Z0-9_\$'"\\\/\[\]\->]+)\s*\n\s*\)/g,
        '$1($2)'
      );

      // Simple 2 args
      code = code.replace(
        /([a-zA-Z0-9_]+)\(\s*\n\s+([^\n,]+),\s*\n\s+([^\n,]+)\s*\n\s*\)/g,
        '$1($2, $3)'
      );

      // PHP/JS arrays: array(\n 'a',\n 'b'\n)
      code = code.replace(
        /(?:array|\[)\s*\n\s+(['"][a-zA-Z0-9_\s\-]+['"]),\s*\n\s+(['"][a-zA-Z0-9_\s\-]+['"]),?\s*\n\s*(?:\)|\])/g,
        '[$1, $2]'
      );
    }
  }

  // 5. Normalize excessive blank lines
  if (options.normalizeBlankLines) {
    code = code.replace(/(\r?\n\s*){3,}/g, '\n\n');
    code = code.replace(/\{\s*\n\s*\n+/g, '{\n');
    code = code.replace(/\n\s*\n+(\s*\})/g, '\n$1');
  }

  const originalLines = rawCode.split(/\r?\n/).length;
  const cleanedLines = code.split(/\r?\n/).length;
  const linesReduced = Math.max(0, originalLines - cleanedLines);

  return {
    cleanedCode: code.trim(),
    originalLines,
    cleanedLines,
    linesReduced,
  };
}
